sonata_admin:
    title: 'Playfulkit'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }

        groups:
            app.admin.group.superadmin:
                label: Super admin
                items:
                    - admin.user
                    - admin.blog
                    - admin.customer
                    - admin.message
                roles: ['ROLE_SUPER_ADMIN']

            app.admin.group.admin:
                label: Admin
                items:
                    - admin.tutorial
                    - admin.category
                    - admin.lesson
                    - admin.tool
                roles: ['ROLE_ADMIN']


sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
