vich_uploader:
    db_driver: orm

    mappings:
        tutorial_image:
            uri_prefix: /images/tutorial
            upload_destination: '%kernel.project_dir%/public/images/tutorial'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
